# environment-specific overrides for dev
replicaCount: 1
image:
  repository: ghcr.io/sriniboosaraju/myapp-db
  tag: "fb8e5b2"
  pullPolicy: Always
# Database addon
database:
  enabled: true
  secretName: myapp-db-credentials
service:
  type: LoadBalancer
  port: 80
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "classic"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "automation:destroy-date=2026-12-31"
