replicaCount: 1

image:
  repository: ghcr.io/sriniboosaraju/myapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "classic"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "automation:destroy-date=2026-12-31"

# Database addon configuration
database:
  enabled: false
  secretName: myapp-db-credentials

resources: {}
