# Production environment overrides
replicaCount: 3
image:
  repository: ghcr.io/sriniboosaraju/myapp
  tag: "004829c"

# Database addon
database:
  enabled: true
  secretName: myapp-db-credentials
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 80
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "automation:destroy-date=2027-12-31,environment=production"
env:
  - name: NODE_ENV
    value: "production"
  - name: LOG_LEVEL
    value: "warn"
  - name: APP_NAME
    value: "myapp-prod"
  - name: REGION
    value: "us-east-1"
resources:
  requests:
    memory: "128Mi"
    cpu: "200m"
  limits:
    memory: "256Mi"
    cpu: "500m"
